server:
  port: 8080
  servlet:
    encoding:
      charset: utf-8

spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: 
  
  h2:
    console:
      enabled: true
  
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    properties:
      '[hibernate.format_sql]': true
  
  output:
    ansi:
      enabled: always

file:
  path: C:/sts-4.14.0.RELEASE/workspace/images/

logging:
  level:
    '[org.springframework.web]': DEBUG
    '[org.hibernate]': DEBUG